[package]
name = "zokrates-pest-ast"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]
edition = "2018"

[dependencies]
zokrates_pest = { git = "https://github.com/JacobEberhardt/ZoKratesGrammarSpecPEG", version = "0.1.0" }
zokrates_core = { path = "../zokrates/zokrates_core" }
zokrates_field = { path = "../zokrates/zokrates_field" }
pest = "2.0"
