version: 2

jobs:
  build:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check format
          command: rustup component add rustfmt-preview; cargo fmt --all -- --check
      - run:
          name: Run tests
          command: cargo test

workflows:
  version: 2
  test:
    jobs:
      - build


